name: Navid Paya
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
author:
  email:    'mailto:me@navidpaya.com'
  blog:     "http://blog.navidpaya.com/"
  linkedin: "https://my.linkedin.com/in/navidpaya"
  github:   "https://github.com/navidpaya"
